spring:
  application:
    name: demo

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3307/AdidarkDB
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

jwt:
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
  expiration: 86400 # 1 Day

vnpay:
  pay_url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return_url: /vnpay-payment-return
  vnp_TmnCode: 48IK86R2
  vnp_HashSecret: R2W1B77T9P72GIIIMTDRZ7ATR3K7U2WC
  vnp_apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction